---
# file: roles/apache2/tasks/main.yml
# This playbook contains apache2 plays that will be run on webservers nodes.

- name: install apache2
  apt: pkg={{ item }} state=installed
  with_items:
    - apache2
    - apache2-doc
    - apache2-utils
    - libexpat1
    - ssl-cert
  #sudo: yes

- name: create webapp vhost
  template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf
  #sudo: yes

- name: a2ensite webapp
  command: a2ensite {{ domain }}
  args:
    creates: /etc/apache2/site-enabled/{{ domain }}.conf
  notify:
    - restart apache2
  #sudo: yes

- name: activation mod-rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2
  #sudo: yes

