---
# file: roles/php/tasks/main.yml
# This playbook contains php plays that will be run on all nodes.

- name: install PHP
  apt: pkg={{ item }} state=installed
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-common
    - php5-curl
    - php5-dev
    - php5-gd
    - php5-intl
    - php-pear
    - php5-imagick
    - php5-imap
    - php5-json
    - php5-mcrypt
    - php5-memcache
    - php5-mysql
    - php5-pspell
    - php5-recode
    - php5-xmlrpc
    - php5-xsl
    - mysql-server

- name: Modify date.time zone in different files
  replace:
    dest: {{ item }}
    regexp=';date.timezone ='
    replace='date.time = Europe/Paris'
    backup=yes
    with_items:
      - /etc/php5/apache2/php.ini
      - /etc/php5/cli/php.ini

- name: Add custom mysql config collation-server
  lineinfile:
    dest=/etc/mysql/my.cnf
    insertafter=EOF
    line={{ item }}
    with_items:
      - "collation-server = utf8_general_ci"
      - "character-set-server = utf8"

- name: restart mysql
  service: name=mysql state=restarted

- name: create webapp db
  mysql_db:
    name=webapp
    state=present

